# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
Charity.create(name: "Lifesong for Orphans", description: "Lifesong for Orphans seeks to mobilize the Church, His body, where each member can provide a unique and special service: some to adopt, some to care, some to give. A struggling business, a simple vow to further God's Kingdom, and many divine encounters. These would be used as catalysts to begin, what is now, Lifesong for Orphans. With a family culture and a heart for the world's fatherless, Lifesong for Orphans offers adoption financial assistance, foster care support, church and ministry partnerships, and international orphan care by serving advocates who help carry out this work of bringing joy and purpose to orphans." , rating: 4)
Charity.create(name: "Equal Justice Initiative", description: "EJI is committed to ending mass incarceration and excessive punishment in the United States, to challenging racial and economic injustice, and to protecting basic human rights for the most vulnerable people in American society. 
  Founded in 1989 by Bryan Stevenson, a widely acclaimed public interest lawyer and bestselling author of Just Mercy, EJI provides legal representation to people who have been illegally convicted, unfairly sentenced, or abused in state jails and prisons. We challenge the death penalty and excessive punishment and we provide re-entry assistance to formerly incarcerated people. 
  EJI works with communities that have been marginalized by poverty and discouraged by unequal treatment. We are committed to changing the narrative about race in America. In 2018, EJI plans to build a national memorial to victims of lynching and open a museum that explores African American history from enslavement to mass incarceration." , rating: 4)
Charity.create(name: "Hope for Haiti's Children", description: "Hope For Haiti's Children (HFHC) is a faith-based organization founded in 1995 in order to demonstrate Christian compassion to poverty-bound Haitian children and their families, providing opportunities for these children to become leaders in their homes, churches, and communities. Today, there are over 1,600 children sponsored in ten different schools associated with churches of Christ in central and southern Haiti. Currently Hope for Haiti's Children average 100 new students per year to the Child Education Sponsorship program. HFHC follows a sustainable approach in this work, having established an in-country network of trusted local Christian educators, business leaders, and other professionals who carry out the day-to-day operations." , rating: 4)
Charity.create(name: "Kids Alive International", description: "Kids Alive International is a Christian faith mission dedicated to rescuing orphans and vulnerable children - meeting their spiritual, physical, educational, and emotional needs - raising them to be contributing members of their society and witnesses to their family and community. Founded in 1916, Kids Alive International began providing homes for homeless children. Since that time, Kids Alive has expanded to include not only children's homes but also care centers and schools. These programs provide orphans and abandoned children with an education, clothing, food, medical care (in some cases), and most importantly, the love of Christ." , rating: 4)
Charity.create(name: "Direct Relief", description: "Direct Relief is a humanitarian aid organization, active in all 50 states and more than 80 countries, with a mission to improve the health and lives of people affected by poverty or emergencies.
Nongovernmental, nonsectarian, and not-for-profit, Direct Relief provides assistance to people and communities without regard to politics, religion, ethnic identities or ability to pay. 
Direct Relief's assistance programs - which focus on emergency preparedness and disaster response and the prevention and treatment of disease - are tailored to the particular circumstances and needs of the world's most vulnerable and at-risk populations.
Direct Relief honors the generosity of its donors by following a firm policy of full transparency in all of its operations.
This tradition of transparent, direct and targeted assistance, provided in a manner that respects and involves the people served, has been a hallmark of the organization since its founding in 1948 by refugee war immigrants to the U.S." , rating: 4)
Charity.create(name: "Global Greengrants Fund
", description: "Founded in 1993 to support grassroots projects and policy for social environmental justice around the world, Global Greengrants Fund works through networks of over 120 on-the-ground volunteer advisors to locate dynamic, effective projects in environmental justice, preservation, and policy; by year-end 2010 Greengrants will have donated $24 million to 129 developing countries. The fund aims to serve the poorest countries of the world. Poor, rural and indigenous communities not only suffer most the consequences of shifts in rainfall, rising seas, and increased climate variability, they are also the most vulnerable due to economic and environmental policies of the countries in which they live." , rating: 4)
Charity.create(name: "The Mission Continues", description: "The Mission Continues is a national nonprofit organization that empowers veterans who are adjusting to life at home to find purpose through community impact. Our operations in cities across the country deploy veteran volunteers alongside non-profit partners and community leaders to solve some of the most challenging issues facing our communities: improving community education resources, eliminating food deserts, mentoring at-risk youth and more. Through six-month service fellowships, individual veterans all across the country make an impact on issues of importance to them and their communities. Through this unique approach, veterans build new skills and networks that help them successfully reintegrate to life after the military while making long-term, sustainable transformations in communities and inspiring future generations to serve." , rating: 4)